#!/bin/bash

current=$(dirname $0)
Date=$(date +%d_%m_%y)
[ -f $current/$Date.txt ] || touch $current/$Date.txt

#name="Report"
#touch $name:$Date 
top -b -n1 > $current/top.txt

Time=$(date +%H)
echo -n "$Time " >> $current/$Date.txt

Cpu=$(grep "%Cpu(s)" $current/top.txt | awk '{print $(2)}') 
echo -n "$Cpu " >> $current/$Date.txt
grep "KiB Mem" $current/top.txt | awk '{print $(NF-3)}' >> $current/$Date.txt

rm $current/top.txt

if [ $Time == 23 ]; then
	python $current/send_report.py $current/$Date.txt
fi

echo "script executed successfully"

