#!/bin/bash

Date=$(date +%d_%m_%y)
[ -f $Date.txt ] || touch $Date.txt

#name="Report"
#touch $name:$Date 
top -b -n1 > top.txt

Time=$(date +%H)
echo -n "$Time " >> $Date.txt

flag=0
while read line; do
    for word in $line; do
    	if [ $flag == 1 ]; then
    		echo -n "$word " >> $Date.txt
    		flag=0
    	fi
    	if [ $flag == 2 ]; then
    		echo $word  >> $Date.txt
    		flag=3
    		break
    	fi
        if [ $word == "%Cpu(s):" ]; then
        	flag=1
        fi
        if [ $word == "free," ]; then
        	flag=2
        fi
    done
    if [ $flag == 3 ]; then
    	break
    fi
done <  top.txt

rm top.txt
if [ $Time == 23 ]; then
	python system_load_graph.py $Date.txt
fi


