#!/bin/bash

current=$(dirname $0) #store the absolute path to the current directory
Date=$(date +%d_%m_%y)
[ -f $current/$Date.txt ] || touch $current/$Date.txt # make file if not present 

hour_temp=$(date +%H)
hours=${hour_temp#0}
min_temp=$(date +%M)
mins=${min_temp#0}
sec_temp=$(date +%S)
secs=${sec_temp#0}
until [[ $hours -eq "23" ]] && [[ $mins -eq "59" ]] && [[ $secs -eq "59" ]] #run till the last sec of the day
do
	Time=$(date +%H_%M_%S)
	hour_temp=$(date +%H)
	hours=${hour_temp#0}    #strip trailing 0
	min_temp=$(date +%M)
	mins=${min_temp#0}	
	sec_temp=$(date +%S)
	secs=${sec_temp#0}
	total_secs=$(( (hours*60 + mins)*60 + secs ))
	echo -n "$total_secs " >> $current/$Date.txt
	Cpu=$(mpstat 1 1| grep -A 5 "%idle" | tail -n 1 | awk -F " " '{print 100 -  $12}') 
	echo -n "$Cpu " >> $current/$Date.txt
	vmstat -s | grep "used memory" | awk '{print $1}' >> $current/$Date.txt
	
done

python $current/send_report.py $current/$Date.txt  

sleep 1

$current/system_load

echo "script executed successfully"



